-- Every row must return true before beta deployment.
select 'profiles_table' as check_name,to_regclass('public.profiles') is not null as passed;
select 'cards_table',to_regclass('public.cards') is not null;
select 'player_cards_table',to_regclass('public.player_cards') is not null;
select 'system_card_pool_table',to_regclass('public.system_card_pool') is not null;
select 'market_listings_table',to_regclass('public.market_listings') is not null;
select 'market_bids_table',to_regclass('public.market_bids') is not null;
select 'gold_ledger_table',to_regclass('public.gold_ledger') is not null;
select 'app_settings_table',to_regclass('public.app_settings') is not null;
select 'rate_limits_table',to_regclass('public.rate_limit_buckets') is not null;
select 'economy_events_table',to_regclass('public.economy_events') is not null;
select 'economy_daily_summaries_table',to_regclass('public.economy_daily_summaries') is not null;
select 'admin_audit_table',to_regclass('public.admin_audit_log') is not null;
select 'database_maintenance_function',to_regprocedure('public.run_database_maintenance(integer)') is not null;
select 'sync_energy_function',to_regprocedure('public.sync_energy()') is not null;
select 'produce_energy_function',to_regprocedure('public.produce_energy(integer)') is not null;
select 'buy_upgrade_function',to_regprocedure('public.buy_upgrade(text)') is not null;
select 'open_pack_function',to_regprocedure('public.open_pack(text)') is not null;
select 'pack_status_function',to_regprocedure('public.get_pack_status()') is not null;
select 'convert_gold_function',to_regprocedure('public.convert_energy_to_gold(integer)') is not null;
select 'create_fixed_listing_function',to_regprocedure('public.create_fixed_listing(uuid,bigint)') is not null;
select 'create_auction_listing_function',to_regprocedure('public.create_auction_listing(uuid,bigint,integer)') is not null;
select 'buy_listing_function',to_regprocedure('public.buy_market_listing(uuid)') is not null;
select 'place_bid_function',to_regprocedure('public.place_auction_bid(uuid,bigint)') is not null;
select 'settle_auctions_function',to_regprocedure('public.settle_expired_auctions()') is not null;
select 'system_buyback_function',to_regprocedure('public.sell_card_to_system(uuid)') is not null;
select 'card_price_stats_function',to_regprocedure('public.get_card_price_stats(uuid,public.card_variant)') is not null;
select 'watchlist_table',to_regclass('public.card_watchlist') is not null;
select 'notifications_table',to_regclass('public.notifications') is not null;
select 'set_card_watch_function',to_regprocedure('public.set_card_watch(uuid,public.card_variant,bigint)') is not null;
select 'mark_notifications_read_function',to_regprocedure('public.mark_notifications_read(uuid)') is not null;
select 'friday_market_function',to_regprocedure('public.ensure_friday_market()') is not null;
select 'create_trade_function',to_regprocedure('public.create_trade_offer(uuid,uuid[],uuid[],bigint,bigint,integer)') is not null;
select 'accept_trade_function',to_regprocedure('public.accept_trade_offer(uuid)') is not null;
select 'card_fusions_table',to_regclass('public.card_fusions') is not null;
select 'fuse_cards_function',to_regprocedure('public.fuse_card_copies(uuid,public.card_variant)') is not null;
select 'scoreboard_function',to_regprocedure('public.get_scoreboard(integer)') is not null;
select 'profiles_rls',(select relrowsecurity from pg_class where oid='public.profiles'::regclass);
select 'player_cards_rls',(select relrowsecurity from pg_class where oid='public.player_cards'::regclass);
select 'market_rls',(select relrowsecurity from pg_class where oid='public.market_listings'::regclass);
select 'ledger_rls',(select relrowsecurity from pg_class where oid='public.gold_ledger'::regclass);
select 'seed_upgrades',(select count(*)>=4 from public.upgrades);
select 'seed_packs',(select count(*)>=3 from public.pack_types);
select 'beta_badge',(select count(*)=1 from public.badges where key='beta-player');
select 'negative_balances_impossible',not exists(select 1 from public.profiles where energy<0 or total_energy<0 or gold<0);
select 'invalid_supply_impossible',not exists(select 1 from public.cards where minted_supply<0 or (max_supply is not null and minted_supply>max_supply));
select 'duplicate_active_listing_impossible',not exists(select player_card_id from public.market_listings where status='active' and player_card_id is not null group by player_card_id having count(*)>1);
select 'orphan_player_cards_impossible',not exists(select 1 from public.player_cards pc left join public.profiles p on p.id=pc.owner_id left join public.cards c on c.id=pc.card_id where p.id is null or c.id is null);
select 'invalid_auction_impossible',not exists(select 1 from public.market_listings where listing_type='auction' and ends_at is null);
