begin;
select plan(6);
select has_table('public','card_watchlist','watchlist table exists');
select has_table('public','notifications','notifications table exists');
select has_function('public','set_card_watch',array['uuid','card_variant','bigint'],'set watch RPC exists');
select has_function('public','remove_card_watch',array['uuid','card_variant'],'remove watch RPC exists');
select has_function('public','mark_notifications_read',array['uuid'],'mark read RPC exists');
select function_privs_are('public','mark_notifications_read',array['uuid'],'authenticated',array['EXECUTE'],'authenticated can mark own notifications');
select * from finish();
rollback;
