begin;

create table if not exists public.card_watchlist(owner_id uuid not null references public.profiles(id) on delete cascade,card_id uuid not null references public.cards(id) on delete cascade,variant public.card_variant not null default 'Standard',target_price bigint check(target_price is null or target_price>0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(owner_id,card_id,variant));
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles(id) on delete cascade,type text not null,title text not null,body text not null default '',reference_id uuid,metadata jsonb not null default '{}'::jsonb,read_at timestamptz,created_at timestamptz not null default now());
create index if not exists watchlist_card_target_idx on public.card_watchlist(card_id,variant,target_price);
create index if not exists notifications_owner_unread_idx on public.notifications(owner_id,created_at desc) where read_at is null;
create unique index if not exists notifications_reference_once_idx on public.notifications(owner_id,type,reference_id) where reference_id is not null;

create or replace function public.notify_watchlist_price() returns trigger language plpgsql security definer set search_path=public as $$ begin if new.status='active' then insert into public.notifications(owner_id,type,title,body,reference_id,metadata) select w.owner_id,'watchlist_price','İzlediğin kart hedef fiyata indi',c.name||' '||new.price||' Gold fiyatla pazarda.',new.id,jsonb_build_object('card_id',new.card_id,'listing_id',new.id,'price',new.price,'variant',coalesce(new.card_variant,'Standard')) from public.card_watchlist w join public.cards c on c.id=w.card_id where w.card_id=new.card_id and w.variant=coalesce(new.card_variant,'Standard') and w.target_price is not null and new.price<=w.target_price on conflict do nothing; end if;return new;end $$;
drop trigger if exists market_watchlist_price_alert on public.market_listings;
create trigger market_watchlist_price_alert after insert or update of status,price on public.market_listings for each row execute function public.notify_watchlist_price();

create or replace function public.notify_listing_sale() returns trigger language plpgsql security definer set search_path=public as $$ declare paid bigint;begin if new.status='sold' and old.status is distinct from 'sold' then paid:=coalesce(new.current_bid,new.price);if new.seller_id is not null then insert into public.notifications(owner_id,type,title,body,reference_id,metadata) values(new.seller_id,'card_sold','Kartın satıldı',paid||' Gold değerinde satış tamamlandı.',new.id,jsonb_build_object('card_id',new.card_id,'price',paid)) on conflict do nothing;end if;if new.listing_type='auction' and new.current_bidder is not null then insert into public.notifications(owner_id,type,title,body,reference_id,metadata) values(new.current_bidder,'auction_won','Açık artırmayı kazandın',paid||' Gold karşılığında kart koleksiyonuna eklendi.',new.id,jsonb_build_object('card_id',new.card_id,'price',paid)) on conflict do nothing;end if;end if;return new;end $$;
drop trigger if exists market_sale_notification on public.market_listings;
create trigger market_sale_notification after update of status on public.market_listings for each row execute function public.notify_listing_sale();

create or replace function public.notify_outbid() returns trigger language plpgsql security definer set search_path=public as $$ declare previous_bidder uuid;begin select current_bidder into previous_bidder from public.market_listings where id=new.listing_id;if previous_bidder is not null and previous_bidder<>new.bidder_id then insert into public.notifications(owner_id,type,title,body,reference_id,metadata) values(previous_bidder,'outbid','Teklifin geçildi','Açık artırmada daha yüksek bir teklif verildi.',new.listing_id,jsonb_build_object('listing_id',new.listing_id,'new_bid',new.amount)) on conflict(owner_id,type,reference_id) where reference_id is not null do update set metadata=excluded.metadata,read_at=null,created_at=now();end if;return new;end $$;
drop trigger if exists market_bid_outbid_notification on public.market_bids;
create trigger market_bid_outbid_notification after insert on public.market_bids for each row execute function public.notify_outbid();

create or replace function public.set_card_watch(p_card uuid,p_variant public.card_variant,p_target_price bigint default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid();result public.card_watchlist;begin if uid is null then raise exception 'AUTH_REQUIRED';end if;if p_target_price is not null and p_target_price<1 then raise exception 'INVALID_PRICE';end if;if not exists(select 1 from public.cards where id=p_card and is_active) then raise exception 'CARD_NOT_FOUND';end if;insert into public.card_watchlist(owner_id,card_id,variant,target_price) values(uid,p_card,p_variant,p_target_price) on conflict(owner_id,card_id,variant) do update set target_price=excluded.target_price,updated_at=now() returning * into result;return to_jsonb(result);end $$;
create or replace function public.remove_card_watch(p_card uuid,p_variant public.card_variant) returns boolean language plpgsql security definer set search_path=public as $$ begin if auth.uid() is null then raise exception 'AUTH_REQUIRED';end if;delete from public.card_watchlist where owner_id=auth.uid() and card_id=p_card and variant=p_variant;return found;end $$;
create or replace function public.mark_notifications_read(p_notification uuid default null) returns integer language plpgsql security definer set search_path=public as $$ declare changed integer;begin if auth.uid() is null then raise exception 'AUTH_REQUIRED';end if;update public.notifications set read_at=now() where owner_id=auth.uid() and read_at is null and(p_notification is null or id=p_notification);get diagnostics changed=row_count;return changed;end $$;
create or replace function public.refresh_daily_notification() returns boolean language plpgsql security definer set search_path=public as $$ declare uid uuid:=auth.uid();today date:=(timezone('utc',now()))::date;begin if uid is null then raise exception 'AUTH_REQUIRED';end if;if exists(select 1 from public.pack_types where daily and is_active) and not exists(select 1 from public.daily_claims where owner_id=uid and claim_date=today) and not exists(select 1 from public.notifications where owner_id=uid and type='daily_ready' and metadata->>'ready_date'=today::text) then insert into public.notifications(owner_id,type,title,body,metadata) values(uid,'daily_ready','Günlük paketin hazır','Ücretsiz günlük paketini açabilirsin.',jsonb_build_object('ready_date',today));return true;end if;return false;end $$;
create or replace function public.notify_maintenance_announcement() returns trigger language plpgsql security definer set search_path=public as $$ begin if new.key='maintenance' and coalesce((new.value->>'enabled')::boolean,false) and(old.value is distinct from new.value) then insert into public.notifications(owner_id,type,title,body,metadata) select id,'announcement','Bakım duyurusu',coalesce(new.value->>'message','Planlı bakım çalışması başladı.'),jsonb_build_object('estimated_end',new.value->>'estimated_end') from public.profiles;end if;return new;end $$;
drop trigger if exists maintenance_announcement_notification on public.app_settings;create trigger maintenance_announcement_notification after update on public.app_settings for each row execute function public.notify_maintenance_announcement();

alter table public.card_watchlist enable row level security;alter table public.notifications enable row level security;
drop policy if exists watchlist_owner_read on public.card_watchlist;create policy watchlist_owner_read on public.card_watchlist for select to authenticated using(auth.uid()=owner_id);
drop policy if exists notifications_owner_read on public.notifications;create policy notifications_owner_read on public.notifications for select to authenticated using(auth.uid()=owner_id);
grant select on public.card_watchlist,public.notifications to authenticated;
revoke all on function public.set_card_watch(uuid,public.card_variant,bigint) from public,anon;revoke all on function public.remove_card_watch(uuid,public.card_variant) from public,anon;revoke all on function public.mark_notifications_read(uuid) from public,anon;revoke all on function public.refresh_daily_notification() from public,anon;
revoke all on function public.notify_watchlist_price() from public,anon,authenticated;revoke all on function public.notify_listing_sale() from public,anon,authenticated;revoke all on function public.notify_outbid() from public,anon,authenticated;revoke all on function public.notify_maintenance_announcement() from public,anon,authenticated;
grant execute on function public.set_card_watch(uuid,public.card_variant,bigint) to authenticated;grant execute on function public.remove_card_watch(uuid,public.card_variant) to authenticated;grant execute on function public.mark_notifications_read(uuid) to authenticated;grant execute on function public.refresh_daily_notification() to authenticated;

commit;
